[build]
target = "x86_64-unknown-uefi"

[target.x86_64-unknown-uefi]
rustflags = [
	"-C", "link-arg=-fuse-ld=lld",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"] 
build-std-features = ["compiler-builtins-mem"]
